// <auto-generated />
using System;
using CodeInsight.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CodeInsight.Web.Migrations
{
    [DbContext(typeof(CodeInsightDbContext))]
    partial class CodeInsightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeInsight.Data.JobExecution.JobExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int>("Progress");

                    b.Property<string>("Result");

                    b.HasKey("Id");

                    b.ToTable("JobExecutions");
                });

            modelBuilder.Entity("CodeInsight.Data.PullRequest.PullRequest", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Additions");

                    b.Property<string>("AuthorId");

                    b.Property<DateTimeOffset?>("ClosedAt");

                    b.Property<int>("CommentCount");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int>("Deletions");

                    b.Property<DateTimeOffset?>("MergedAt");

                    b.Property<string>("RepositoryId");

                    b.Property<string>("Title");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("CodeInsight.Data.Repository.Repository", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.HasKey("Id");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("CodeInsight.Data.PullRequest.PullRequest", b =>
                {
                    b.HasOne("CodeInsight.Data.Repository.Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
